run_name: aigcode-7B_moe_neo_4m_base_continue
seed: 6198
dry_run: false
gpu_type: ascend

# wandb:
#   name: ${run_name}
#   project: aigcode-small
# wandb:
#  entity: liuzimo22
#  name: ${run_name}
#  project: aigcode_pretrain_7B
#  group: aigcode-7B_v1.0

model:
  d_model: 4096
  n_heads: 32
  n_layers: 22
  mlp_ratio: 4
  weight_tying: false
  alibi: false
  rope: true
  rope_base: 30000
  flash_attention: false  # not available on AMD
  attention_dropout: 0.0
  attention_layer_norm: false
  multi_query_attention: false
  include_bias: false
  block_type: sequential
  layer_norm_type: default
  layer_norm_with_affine: false
  bias_for_layer_norm: false
  attention_layer_norm_with_affine: false
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 4096
  # vocab_size: 50280
  # embedding_size: 50304
  # eos_token_id: 0
  # pad_token_id: 1
  vocab_size: 64000
  embedding_size: 65280
  # eos_token_id: 151643
  # pad_token_id: 1
  eos_token_id: 2
  pad_token_id: 0
  init_device: meta
  # init_fn: mitchell
  init_std: 0.01
  gate_softmax_temperature: 8.0
  intermediate_size: 16384
  # intermediate_size: 24576

  use_xmoe: true
  use_ple: false
  ple_layer_num: 0
  ple_layernorm: false
  moe_freq: 2
  # moe_act_ckpt_ratio: 1
  moe_topn_expert: 1
  moe_top1_expert: true
  # gate_level: sample
  gate_level: token
  # gate_sample_ratio: 32
  # moe_gate_input_type: stack
  moe_logging: true
  exp_dim_ratio: 1
  moe_expert_count: 4
  moe_share_expert_count: 0
  moe_gate_loss_weight: 0.
  moe_gate_loss_combine_method: average
  moe_gating_use_fp32: true
  # moe_second_expert_policy: no_sampling
  moe_second_expert_policy: sampling
  moe_normalize_gate_prob_before_dropping: false
  moe_auxiliary_loss: false
  # moe_auxiliary_loss_weight: 0.1
  moe_gate_no_grad: false

moe_logging: true
train_eval: true
distributed_strategy: fsdp
compile: null  # causes instability on AMD GPUs

optimizer:
  name: adamw
  learning_rate: 3.0e-4
  weight_decay: 0.1
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 10

scheduler:
  name: cosine_with_warmup
  t_warmup: 5000
  alpha_f: 0.1
  grad_clip_warmup_steps: 1000
  grad_clip_warmup_factor: 10.0

tokenizer:
  identifier: tokenizers/neo_tokenizer.json
  truncate_direction: right

save_folder: ${path.choose:${oc.env:SCRATCH_DIR,no_exist}/checkpoints,/results}/${oc.env:SLURM_JOB_ID,${run_name}}
save_overwrite: false
# Sharded checkpoints (best for restarts)
save_interval: 1000000
save_num_checkpoints_to_keep: 0
# Unsharded checkpoints (for final storage)
save_interval_unsharded: 360000
save_num_unsharded_checkpoints_to_keep: -1

load_path: /sharedata/aigcode_7b_checkpoints/814/step50400-unsharded
reset_optimizer_state: true
reset_trainer_state: true

# max_duration: 739_328  # 3.1T tokens
max_duration: 285000
# global_train_batch_size: 1280
# device_train_microbatch_size: 2
global_train_batch_size: 64
device_train_microbatch_size: 2
# activation_checkpointing: one_in_two

precision: amp_bf16
# precision: fp32

# fsdp:
#   wrapping_strategy: null
#   precision: mixed
# activation_checkpointing: whole_layer
activation_checkpointing: one_in_two
# activation_checkpointing: three_in_four
# activation_checkpointing: one_in_three


fsdp:
  wrapping_strategy: by_block
  # wrapping_strategy: null
  sharding_strategy: HYBRID_SHARD
  # sharding_strategy: _HYBRID_SHARD_ZERO2
  # sharding_strategy: SHARD_GRAD_OP
  # sharding_strategy: FULL_SHARD
  # use_orig_params: true
  # hybrid_sharding_num_model_replicas: 
  precision: mixed

max_grad_norm: 1.0
max_grad_norm_ratio: null
moe_params_isolation: false
# moe_expert_lr_scale: 1.5
# moe_grad_norm_scale: 1.2

speed_monitor:
  window_size: 20

eval_interval: 500
eval_subset_num_batches: -1
device_eval_batch_size: ${device_train_microbatch_size}
evaluators:
  - label: m-a-p-small-ppl-validation
    data:
      num_workers: 0
      drop_last: true
      datasets:
        book-validation:
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/book_all.0000.jsonl.npy
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/book_biographies_of_characters.0000.jsonl.npy
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/book_education.0000.jsonl.npy
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/book_finance.0000.jsonl.npy
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/book_law.0000.jsonl.npy
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/book_math.0000.jsonl.npy
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/book_medical.0000.jsonl.npy
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/book_reviews.0000.jsonl.npy
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/book_science.0000.jsonl.npy
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/book_technology.0000.jsonl.npy
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/book_textbook.0000.jsonl.npy
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/book_work_report.0000.jsonl.npy
        cc_en-validation:
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/cc_en.0000.jsonl.npy
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/cc_en.0001.jsonl.npy
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/cc_en.0002.jsonl.npy
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/cc_en.0003.jsonl.npy
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/cc_en.0004.jsonl.npy
        cc_zh-validation:
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/cc_zh.0000.jsonl.npy
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/cc_zh.0001.jsonl.npy
        exam-validation:
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/exam_QA.0000.jsonl.npy
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/exam_biology.0000.jsonl.npy
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/exam_math.0000.jsonl.npy
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/exam_math.0001.jsonl.npy
        instruction-validation:
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/instruction_all.0000.jsonl.npy
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/instruction_biology.0000.jsonl.npy
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/instruction_chemistry.0000.jsonl.npy
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/instruction_classification.0000.jsonl.npy
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/instruction_medicine.0000.jsonl.npy
        paper_all-validation:
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/paper_all.0000.jsonl.npy
        wiki_news-validation:
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/wiki_news.0000.jsonl.npy
        wiki_all-validation:
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/wiki_qa.0000.jsonl.npy
        code_all-validation:
          - /sharedata/dataset/m-a-p/Matrix/test_neo/npy/code_code.0003.jsonl.npy

  - label: v3-small-ppl-validation
    data:
      num_workers: 0
      drop_last: true
      datasets:
        v3-small-c4_en-validation:
          - /sharedata/pretrain/npy/eval_neo/v3_small_gptneox20b/c4_en/part-0-00000.npy
        v3-small-dolma_books-validation:
          - /sharedata/pretrain/npy/eval_neo/v3_small_gptneox20b/dolma_books/part-0-00000.npy
        v3-small-dolma_common-crawl-validation:
          - /sharedata/pretrain/npy/eval_neo/v3_small_gptneox20b/dolma_common-crawl/part-0-00000.npy
        v3-small-dolma_pes2o-validation:
          - /sharedata/pretrain/npy/eval_neo/v3_small_gptneox20b/dolma_pes2o/part-0-00000.npy
        v3-small-dolma_reddit-validation:
          - /sharedata/pretrain/npy/eval_neo/v3_small_gptneox20b/dolma_reddit/part-0-00000.npy
        v3-small-dolma_stack-validation:
          - /sharedata/pretrain/npy/eval_neo/v3_small_gptneox20b/dolma_stack/part-0-00000.npy
        v3-small-dolma_wiki-validation:
          - /sharedata/pretrain/npy/eval_neo/v3_small_gptneox20b/dolma_wiki/part-0-00000.npy
        v3-small-ice-validation:
          - /sharedata/pretrain/npy/eval_neo/v3_small_gptneox20b/ice/part-0-00000.npy
        v3-small-m2d2_s2orc-validation:
          - /sharedata/pretrain/npy/eval_neo/v3_small_gptneox20b/m2d2_s2orc/part-0-00000.npy
        v3-small-pile-validation:
          - /sharedata/pretrain/npy/eval_neo/v3_small_gptneox20b/pile/part-0-00000.npy
        v3-small-wikitext_103-validation:
          - /sharedata/pretrain/npy/eval_neo/v3_small_gptneox20b/wikitext_103/part-0-00000.npy

  - label: v2-small-ppl-validation
    data:
      num_workers: 0
      drop_last: true
      datasets:
        v2-small-4chan-validation:
          - /sharedata/pretrain/npy/eval_neo/v2_small_gptneox20b/4chan/val.npy
        v2-small-c4_100_domains-validation:
          - /sharedata/pretrain/npy/eval_neo/v2_small_gptneox20b/c4_100_domains/val.npy
        v2-small-c4_en-validation:
          - /sharedata/pretrain/npy/eval_neo/v2_small_gptneox20b/c4_en/val.npy
        v2-small-gab-validation:
          - /sharedata/pretrain/npy/eval_neo/v2_small_gptneox20b/gab/val.npy
        v2-small-ice-validation:
          - /sharedata/pretrain/npy/eval_neo/v2_small_gptneox20b/ice/val.npy
        v2-small-m2d2_s2orc-validation:
          - /sharedata/pretrain/npy/eval_neo/v2_small_gptneox20b/m2d2_s2orc/val.npy
        v2-small-m2d2_wiki-validation:
          - /sharedata/pretrain/npy/eval_neo/v2_small_gptneox20b/m2d2_wiki/val.npy
        v2-small-manosphere-validation:
          - /sharedata/pretrain/npy/eval_neo/v2_small_gptneox20b/manosphere/val.npy
        v2-small-mc4_en-validation:
          - /sharedata/pretrain/npy/eval_neo/v2_small_gptneox20b/mc4_en/val.npy
        v2-small-pile-validation:
          - /sharedata/pretrain/npy/eval_neo/v2_small_gptneox20b/pile/val.npy
        v2-small-ptb-validation:
          - /sharedata/pretrain/npy/eval_neo/v2_small_gptneox20b/ptb/val.npy
        v2-small-twitterAEE-validation:
          - /sharedata/pretrain/npy/eval_neo/v2_small_gptneox20b/twitterAEE/val.npy
        v2-small-wikitext_103-validation:
          - /sharedata/pretrain/npy/eval_neo/v2_small_gptneox20b/wikitext_103/val.npy


# data:
#   pad_direction: right
#   # num_workers: 16
#   num_workers: 8
#   drop_last: true
#   pin_memory: true
#   prefetch_factor: 16
#   # global_indices_jump: true
#   # file_count : 0
#   persistent_workers: true
#   timeout: 0
#   memmap_dtype: uint16

#   # paths:
#   #   - /sharedata/pretrain/npy/matrix/cc_en/00_cc_en_00000.npy
#   #   - /sharedata/pretrain/npy/matrix/cc_en/00_cc_en_00001.npy
#   #   - /sharedata/pretrain/npy/matrix/cc_en/00_cc_en_00002.npy
#   #   - /sharedata/pretrain/npy/matrix/cc_zh/00_cc_zh_00000.npy
#   #   - /sharedata/pretrain/npy/matrix/code/00_code_code_00000.npy
#   ###
#     # 280G/sharedata/pretrain/npy/matrix_v2/book
#     # 1.3T/sharedata/pretrain/npy/matrix_v2/cc_en
#     # 618G/sharedata/pretrain/npy/matrix_v2/cc_zh
#     # 637G/sharedata/pretrain/npy/matrix_v2/code
#     # 37G/sharedata/pretrain/npy/matrix_v2/exam
#     # 128G/sharedata/pretrain/npy/matrix_v2/instruction
#     # 14G/sharedata/pretrain/npy/matrix_v2/news
#     # 275G/sharedata/pretrain/npy/matrix_v2/paper
#     # 12G/sharedata/pretrain/npy/matrix_v2/patent
#     # 12G/sharedata/pretrain/npy/matrix_v2/wiki
#   ### 
#   ### 785 + 337 + 30 + 140 + 132 + 129 ~ 1.5T
#   # data_dir_prefix: "/sharedata/pretrain/npy/matrix_v2"
#   data_dir_prefix: "/sharedata/pretrain/npy/matrix_neo"
#   data_dir:
#     # 1.7TB 924B token
#     - cc_en: 0.999
#     # 630G 337B token
#     - cc_zh: 0.999
#     # 1.2T 607B token
#     - code: 0.05
#     # # guest 280G 200B token 
#     # - book: 0.999
#     # 353G 189B token
#     - paper: 0.80
#     ### 68 + 19 + 7 + 6 + 3 = 103B
#     # 157G 83B token
#     - instruction: 0.999
#     # 49G 26B token
#     - exam: 0.999
#     # 14G 7.5B token
#     - news: 0.999
#     # 14G 7.1B token
#     - wiki: 0.999
#     # 16G 8.3B token
#     - patent: 0.8